# NUMPY BASICS

In [1]:
import numpy as np

## 1.Array Creation

### Create an array

In [3]:
a = np.array([1,2,3,4,5,6])
print(a)
a.dtype

[1 2 3 4 5 6]


dtype('int64')

### Specify the data type of the array when you create it

In [4]:
c = np.array([1,2,3,4], dtype=float)
print(c)
c.dtype

[1. 2. 3. 4.]


dtype('float64')

### Create an empty array (zeros/ones)

In [7]:
d1 = np.zeros((3,3), dtype=int)
print(d1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
d2 = np.ones((3,3), dtype=int)
print(d2)
d3 = np.empty((3,3), dtype=int)
print(d3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Create arrays with random values

#### float values

In [13]:
F1 = np.random.random(5)
print(F1)

F2 = np.random.random((2,2))
print(F2)

F3 = np.random.random((2,2,2))
print(F3)

[0.37282703 0.05445514 0.60393537 0.0334519  0.5255197 ]
[[0.5083143  0.06746624]
 [0.38659512 0.37002818]]
[[[0.7307315  0.15173565]
  [0.85628424 0.16832412]]

 [[0.52713465 0.29971369]
  [0.62080344 0.04973085]]]


#### integer values

In [15]:
I1 = np.random.randint(0,25, (3,3))   ### 3X3 MATRIX WHICH TAKES VALUES FROM 0 TO 25
print(I1)

I2 = np.random.randint(-50,50,10)     ### 10X1 MATRIX 
print(I2)

[[ 9 12 17]
 [21 20 10]
 [ 5 22 11]]
[ 37 -13  32  -1  30 -17  29  31   4  27]


## 2.Array Manypulation

#### Addition/Subtraction

In [17]:
l1 = np.array([34,76,87])
l2 = np.array([5,7,90])

l = l1-l2
print(l)


[29 69 -3]


#### Element wise multiplication

In [19]:
l_mult = l1*l2
print(l_mult)

[ 170  532 7830]


#### Matrix multiplication

In [27]:
l3 = np.array([[1,2,3],[4,5,6]])          ### A 2X3 MATRIX
l4 = np.array([[6,2],[12,13],[4,67]])     ### A 3X2 MATRIX

l_matrix_mult = l3@l4
print(l_matrix_mult)
print('the size of the dinal matrix is',l_matrix_mult.ndim)

[[ 42 229]
 [108 475]]
the size of the dinal matrix is 2


#### Scalar multiplication/sum/min/max/dimensions/size(total elements)

In [26]:
p = np.array([2,4,6,8])

p_scal2 = p*2
print(p_scal2)

p_sum = p.sum()
print(p_sum)

p_min = p.min()
print(p.min())

p_max = p.max()
print(p.max())

p_dims = p.ndim
print(p.ndim)

p_size = p.size
print(p.size)

[ 4  8 12 16]
20
2
8
1
4


#### Elements based on a condition

In [29]:
r = np.array([[26,28,14,41,31],[45,76,-12,4,6],
              [59,90,-2,8,-13],[3,4,5,6,7],[9,90,2,20,1]])

np.where(r>30,1,0)               ### WHERE r>30 REPLACE WITH 1, ELSE REPLACE WITH 0
np.where(r<0,-1,r)

array([[26, 28, 14, 41, 31],
       [45, 76, -1,  4,  6],
       [59, 90, -1,  8, -1],
       [ 3,  4,  5,  6,  7],
       [ 9, 90,  2, 20,  1]])

#### Indexing

In [36]:
a_3d = np.zeros((3,3,3))
print(a_3d.ndim)
print(a_3d)
print(a_3d[0][0][1])

a_3d[0][0][1] = 12
print(a_3d)

12 in a_3d                   ### CHECK IF 12 IN ARRAY

3
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
0.0
[[[ 0. 12.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


True

#### Slicing

In [41]:
print(r)

print(r[:,:3])             ### GET THE FIRST THREE COLUMNS

print(r[:,1])              ### GET AN ARRAY FROM THE SECOND ELEMENT OF EACH ROW

[[ 26  28  14  41  31]
 [ 45  76 -12   4   6]
 [ 59  90  -2   8 -13]
 [  3   4   5   6   7]
 [  9  90   2  20   1]]
[[ 26  28  14]
 [ 45  76 -12]
 [ 59  90  -2]
 [  3   4   5]
 [  9  90   2]]
[28 76 90  4 90]


#### Reshaping/transpose

In [43]:
r_3x5 = r[:3,:]
print(r_3x5)
r_reshaped = r_3x5.reshape(5,3)
print(r_reshaped)

print(r_reshaped.T)                      ### OR np.transpose(a)

[[ 26  28  14  41  31]
 [ 45  76 -12   4   6]
 [ 59  90  -2   8 -13]]
[[ 26  28  14]
 [ 41  31  45]
 [ 76 -12   4]
 [  6  59  90]
 [ -2   8 -13]]
[[ 26  41  76   6  -2]
 [ 28  31 -12  59   8]
 [ 14  45   4  90 -13]]
